package hi.is.tasker.dto;

import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

@Getter
@Setter
@Accessors(chain = true)
public class LoginUserDto {
    private String username;
    private String password;

    // Getters and Setters are already generated by Lombok
}
